name: deploying the web into EC2
on:
  push:
    branches: [ "master" ]

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: collecting the src from github
        uses: actions/checkout@v7.0.0

      - name: copying the files to working-directory
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "/tmp/website"

      - name: copying the files from working-directory to nginx
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo cp -r /tmp/website/* /var/www/html
            sudo systemctl reload nginx
          
          
    
